### ISSUE TITLE
Frequency of NetworkStatsManager Updats

### ISSUE THREAD

**Issue by octohub** [RobertZagorski/NetworkStats#1]
Robert,

First of all, thank you so much for putting this project together. It has been immensely helpful as I work on my own app on Google Play, NetLive.

My question: I am seeing that the NetworkStatsManager for a given `uid` has much less frequent updates than provided by `TrafficStats`. Is this the case in your experience as well? Is there a way to have NetWorkStatsManager return updated values faster?

Thank you for your help.

**Comment by rajeesh7** [comment]
Thank you for this demo.
I too have similar problem.
I have used the code for getting youtube app usage calculation. I'm getting a constant value every time. 
Even after further youtube usage this value is not incrementing.

Whole device usage calculation is working properly. Only uid calculation is not working.
I heard that bucket size will be updated in an hourly basis. Not sure about this. 
I could see another application from play store which is working properly.
https://play.google.com/store/apps/details?id=com.mobidia.android.mdm

**Comment by RobertZagorski** [comment]
Very probably, the stats for application are updated every 30 minutes, as seen [here](https://android.googlesource.com/platform/frameworks/base/+/master/services/core/java/com/android/server/net/NetworkStatsService.java#1477).
As it is hardcoded value in the system Settings, it cannot be changed.

@rajeesh7 : the application you mentioned is working for android 4.0. That means it is using a different method of checking the app network usage.

**Comment by rajeesh7** [comment]
I agree.
I'm trying to make it using networkstats. Especially for versions starting from M.
For uid app usage calculation, this demo is working in some devices only. I could find outputs in MotoG devices. But same thing is not working in Samsung galaxy A5 and 1+3 devices.

I'm trying to make youtube usage calculation using this demo.
on Sat Jan 14 19:33:37 I got youtube usage value as 158892740.
I have used youtube for an hour.
and on Sat Jan 14 20:50:12 the calculated value is 158892740
ie; the value is not getting updated even after an hour. 
This is happening in some devices only. All other devices are working and is giving correct output.

Any idea ?

**Comment by rajeesh7** [comment]
Also now I'm having another observation.
You are giving 0 in place of starting time. I changed it to a valid time stamp and it is returning as zero usage then.
 public long getAllRxBytesMobile(Context context) {
        NetworkStats.Bucket bucket;
        try {
            bucket = networkStatsManager.querySummaryForDevice(ConnectivityManager.TYPE_MOBILE,
                    getSubscriberId(context, ConnectivityManager.TYPE_MOBILE),
                    1484481120000L,
                    System.currentTimeMillis());
        } catch (RemoteException e) {
            return -1;
        }
        return bucket.getRxBytes();
    }


I'm checking with moto g turbo having android version 6.0.1

**Comment by rajeesh7** [comment]
atlast I got the answer.

  /*
    getting youtube usage for both mobile and wifi. .
     */
    public long getYoutubeTotalusage(Context context) {
        String subId = getSubscriberId(context, ConnectivityManager.TYPE_MOBILE);
        return getYoutubeUsage(ConnectivityManager.TYPE_MOBILE, subId) + getYoutubeUsage(ConnectivityManager.TYPE_WIFI, "");
    }


    private long getYoutubeUsage(int networkType, String subScriberId) {
        NetworkStats networkStatsByApp;
        long currentYoutubeUsage = 0L;
        try {
            networkStatsByApp = networkStatsManager.querySummary(networkType, subScriberId, 0, System.currentTimeMillis());
            do {
                NetworkStats.Bucket bucket = new NetworkStats.Bucket();
                networkStatsByApp.getNextBucket(bucket);
                if (bucket.getUid() == packageUid) {
                    //rajeesh : in some devices this is immediately looping twice and the second iteration is returning correct value. So result returning is moved to the end.
                    currentYoutubeUsage = (bucket.getRxBytes() + bucket.getTxBytes());
                }
            } while (networkStatsByApp.hasNextBucket());

        } catch (RemoteException e) {
            e.printStackTrace();
        }

        return currentYoutubeUsage;
    }


    private String getSubscriberId(Context context, int networkType) {
        if (ConnectivityManager.TYPE_MOBILE == networkType) {
            TelephonyManager tm = (TelephonyManager) context.getSystemService(Context.TELEPHONY_SERVICE);
            return tm.getSubscriberId();
        }
        return "";
    }

**Comment by RobertZagorski** [comment]
I'm glad you worked it out.
I can just add a suggestion, that [`getNextBucket`](https://developer.android.com/reference/android/app/usage/NetworkStats.html#getNextBucket(android.app.usage.NetworkStats.Bucket)) returns the result, whether the reading of info was successful. That might also be the lead, whether data is trustful.

**Comment by bawoodward** [comment]
Thank you very much for this very helpful sample!  

I have a question for you: When I clone and build and install your app from Android Studio (using default debug signature), it works perfectly on my Galaxy S7.  When I integrate aspects of it into my own app, and sign the app with a different signature, when trying to make a call like this: 

```
networkStatsManager.queryDetailsForUid(
                    ConnectivityManager.TYPE_WIFI,
                    "",
                    date.getTimeInMillis(),
                    System.currentTimeMillis(),
                    packageUid);
```
I get the following exception when running on the same device:

02-02 13:44:58.589 E/CustomUncaughtExceptionHandler(20083): Uncaught exception: NetworkStats: Neither user 10289 nor current process has android.permission.READ_NETWORK_USAGE_HISTORY.

I'm confused by this because I see that your app doesn't use this permission, and I don't understand why your app doesn't get this exception even though you haven't requested this permission.  

Can you shed any light on this?

Thanks in advance!

**Comment by RobertZagorski** [comment]
@bawoodward Are you asking for `android:name="android.permission.PACKAGE_USAGE_STATS`? The logic is in function [StatsActivity. hasPermissionToReadNetworkHistory()](https://github.com/RobertZagorski/NetworkStats/blob/master/app/src/main/java/pl/rzagorski/networkstatsmanager/view/StatsActivity.java#L182)

**Comment by bawoodward** [comment]
Got it - thank you VERY much!
