### ISSUE TITLE
for Dual SIM

### ISSUE THREAD

**Issue by shadygoneinsane** [RobertZagorski/NetworkStats#4]
I can see you used `getSubscriberId(context, ConnectivityManager.TYPE_MOBILE)` for fetching out Mobile Data but for dual sim phones how can I categorise or differentiate that which SubscriberId is being used ? Is it for Sim 1 or Sim 2 !!

**Comment by RobertZagorski** [comment]
Hello, In Dual SIM case you might make use of [SubscriptionManager](https://developer.android.com/reference/android/telephony/SubscriptionManager.html)
As `NetworkStats` are available from API 23 and SubscriptionManager from API 22, `NetworkStatsManager` might be used with SubscriptionManager
